[package]
name = "openai_proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.6.1"
http-body-util = "0.1.2"
hyper = { version = "1.4.1", features = ["full"] }
hyper-tls = "0.6.0"
hyper-util = { version = "0.1.6", features = ["full"] }
pretty_env_logger = "0.5.0"
tokio = { version = "1.38.1", features = ["full"] }
